### PR TITLE
parametrize pgbouncer default_pool_size

### PR DESCRIPTION
**Pull request by jfchevrette**
Defaults to 100, can be changed by setting an environment variable

### CODE REVIEW

**Review by yzainee — APPROVED** [review]
LGTM

**Comment by jfchevrette** [comment]
The container does not build anymore because of missing rpms

**Comment by jfchevrette** [comment]
Pushed a change to allow the container to build again
- centos 7 to centos 8
- pgbouncer 1.8.1 to 1.15.1

**Comment by yzainee** [comment]
@jfchevrette We have tested this image in our dev cluster. Have gone through several rounds of verification and taks. We feel its good to go ahead. Do you have any concerns?

cc: @rafiu007 @jparsai 

Ideal is to move it to stage. monitor it for few more days for different operations and eventually move it to prod

**Comment by jfchevrette** [comment]
@yzainee no concerns +1 to deploy it to state and test further

**Comment by yzainee** [comment]
@jparsai @rafiu007 waiting for your +1

**Comment by jparsai** [comment]
+1

**Comment by rafiu007** [comment]
LGTM.

**Review by rafiu007 — APPROVED** [review]

**Pull request merged**
